# -*- coding: utf-8 -*-
"""
Use python bindings to SBGN (generated by generateDS) to interact
with SBGN maps.

generateDS.py -o libsbgn.py -s libsbgnSubs.py SBGN.xsd

@author: Matthias Koenig & Augustin Luna
Created on Mon Apr 20 19:02:22 2015

TODO: export write <?xml version="1.0" encoding="UTF-8"?>
TODO: export no sbgn: prefix

TODO: int() cast of integer values - not string of double
TODO: 

TODO: git repository
TODO: documentation sphynx
TODO: python package

"""
from __future__ import print_function
import libsbgn         # import the bindings
print(libsbgn.__all__)

def print_bbox(b):
    print('x, y, w, h : ', b.get_x(), b.get_y(), b.get_w(), b.get_h())

#################################################################
# read SBGN
#################################################################
f_in = 'examples/adh.sbgn'

# sbgn and map
sbgn = libsbgn.parse(f_in)
map = sbgn.get_map()
print('***', map.get_language(), '***')

# bbox
'''
<bbox x="0" y="0" w="363" h="253"/>
'''
box = map.get_bbox()
print_bbox(box)

# glyphs
'''
<glyph class="simple chemical" id="glyph1">
		<label text="Ethanol"/> <!-- fontsize="" etc -->
		<!-- Line breaks are allowed in the text attribute -->
		<bbox x="40" y="120" w="60" h="60"/>
	</glyph>
'''
glyphs = map.get_glyph()
for g in glyphs:
    cls = g.get_class()
    print(cls, g.get_id())
    label =  g.get_label()
    if cls == 'simple chemical':   
        print('label: ', label.get_text())
        
    if cls == 'process':
        for p in g.get_port():
            print('port ', p.get_id(), p.get_x(), p.get_y())
    
    box = g.get_bbox()
    print_bbox(box)
    print

# arcs
'''
	<arc class="consumption" source="glyph_nad" target="pn1.1" id="a06">
		<start x="95" y="202" />
		<end x="136" y="180" />			
	</arc>
'''
arcs = map.get_arc()
for a in arcs:
    print(a.get_class(), a.get_source(), a.get_target(), a.get_id())
    start = a.get_start()
    print(start.x, start.y)
    end = a.get_end()
    print(end.x, end.y)


#################################################################
# write SBGN
#################################################################
# TODO: write file
sbgn = libsbgn.sbgn()
print(sbgn)

map = libsbgn.map()
sbgn.set_map(map)
print(map)

'''
<bbox x="0" y="0" w="363" h="253"/>
'''
box = libsbgn.bbox()
box.set_x(0)
box.set_y(0)
box.set_w(363)
box.set_h(253)
map.set_bbox(box)

'''
	<glyph class="simple chemical" id="glyph1">
		<label text="Ethanol"/> <!-- fontsize="" etc -->
		<!-- Line breaks are allowed in the text attribute -->
		<bbox x="40" y="120" w="60" h="60"/>
	</glyph>
'''

# export(self, outfile, level, namespace_='sbgn:', name_='sbgn', namespacedef_='xmlns:sbgn="http://sbgn.org/libsbgn/0.2"', pretty_print=True)

f_out = open('examples/test.sbgn', 'w')
sbgn.export(f_out, level=0, namespace_='')
f_out.close()